/*==============================================================================
    Copyright (c) 2001-2010 Joel de Guzman
    Copyright (c) 2010-2011 Thomas Heller

    Distributed under the Boost Software License, Version 1.0. (See accompanying
    file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
==============================================================================*/
    
    namespace placeholders
    {
        typedef expression::argument<1>::type arg1_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<2>::type arg2_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<3>::type arg3_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<4>::type arg4_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<5>::type arg5_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<6>::type arg6_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<7>::type arg7_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<8>::type arg8_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<9>::type arg9_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<10>::type arg10_type BOOST_ATTRIBUTE_UNUSED;
        typedef expression::argument<1>::type _1_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<2>::type _2_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<3>::type _3_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<4>::type _4_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<5>::type _5_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<6>::type _6_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<7>::type _7_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<8>::type _8_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<9>::type _9_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<10>::type _10_type BOOST_ATTRIBUTE_UNUSED;
       BOOST_ATTRIBUTE_UNUSED expression::argument<1>::type const arg1 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<2>::type const arg2 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<3>::type const arg3 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<4>::type const arg4 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<5>::type const arg5 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<6>::type const arg6 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<7>::type const arg7 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<8>::type const arg8 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<9>::type const arg9 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<10>::type const arg10 = {{{}}};
       BOOST_ATTRIBUTE_UNUSED expression::argument<1>::type const _1 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<2>::type const _2 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<3>::type const _3 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<4>::type const _4 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<5>::type const _5 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<6>::type const _6 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<7>::type const _7 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<8>::type const _8 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<9>::type const _9 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<10>::type const _10 = {{{}}};
    }
    namespace arg_names
    {
        typedef expression::argument<1>::type arg1_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<2>::type arg2_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<3>::type arg3_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<4>::type arg4_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<5>::type arg5_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<6>::type arg6_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<7>::type arg7_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<8>::type arg8_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<9>::type arg9_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<10>::type arg10_type BOOST_ATTRIBUTE_UNUSED;
        typedef expression::argument<1>::type _1_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<2>::type _2_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<3>::type _3_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<4>::type _4_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<5>::type _5_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<6>::type _6_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<7>::type _7_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<8>::type _8_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<9>::type _9_type BOOST_ATTRIBUTE_UNUSED; typedef expression::argument<10>::type _10_type BOOST_ATTRIBUTE_UNUSED;
       BOOST_ATTRIBUTE_UNUSED expression::argument<1>::type const arg1 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<2>::type const arg2 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<3>::type const arg3 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<4>::type const arg4 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<5>::type const arg5 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<6>::type const arg6 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<7>::type const arg7 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<8>::type const arg8 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<9>::type const arg9 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<10>::type const arg10 = {{{}}};
       BOOST_ATTRIBUTE_UNUSED expression::argument<1>::type const _1 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<2>::type const _2 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<3>::type const _3 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<4>::type const _4 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<5>::type const _5 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<6>::type const _6 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<7>::type const _7 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<8>::type const _8 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<9>::type const _9 = {{{}}}; BOOST_ATTRIBUTE_UNUSED expression::argument<10>::type const _10 = {{{}}};
    }
